### ISSUE TITLE
# TypeError: function takes exactly 1 argument (3 given)

### ISSUE THREAD

**Issue by ximingxing** [tristandeleu/pytorch-maml#4]
```bash
root@223b941646ee:/Github/pytorch-maml# python train.py /few-shot-datasets --dataset omniglot --num-ways 5 --num-shots 1 --use-cuda --step-size 0.4 --batch-size 32 --num-workers 8 --num-epochs 600 --output-folder /path/to/results
INFO:root:Saving configuration file in `/path/to/results/2020-01-11_123958/config.json`
Traceback (most recent call last):
  File "train.py", line 197, in <module>
    main(args)
  File "train.py", line 114, in main
    verbose=args.verbose, desc='Training', leave=False)
  File "/Github/pytorch-maml/maml/metalearners/maml.py", line 171, in train
    for results in self.train_iter(dataloader, max_batches=max_batches):
  File "/Github/pytorch-maml/maml/metalearners/maml.py", line 189, in train_iter
    for batch in dataloader:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.6/dist-packages/torchmeta-1.2.1-py3.6.egg/torchmeta/utils/data/dataloader.py", line 22, in _collate_fn
    return collate_fn([collate_task(task) for task in batch])
  File "/usr/local/lib/python3.6/dist-packages/torchmeta-1.2.1-py3.6.egg/torchmeta/utils/data/dataloader.py", line 22, in <listcomp>
    return collate_fn([collate_task(task) for task in batch])
  File "/usr/local/lib/python3.6/dist-packages/torchmeta-1.2.1-py3.6.egg/torchmeta/utils/data/dataloader.py", line 17, in collate_task
    for (key, subtask) in task.items()])
  File "/usr/local/lib/python3.6/dist-packages/torchmeta-1.2.1-py3.6.egg/torchmeta/utils/data/dataloader.py", line 17, in <listcomp>
    for (key, subtask) in task.items()])
  File "/usr/local/lib/python3.6/dist-packages/torchmeta-1.2.1-py3.6.egg/torchmeta/utils/data/dataloader.py", line 14, in collate_task
    return collate_fn([task[idx] for idx in range(len(task))])
  File "/usr/local/lib/python3.6/dist-packages/torchmeta-1.2.1-py3.6.egg/torchmeta/utils/data/dataloader.py", line 14, in <listcomp>
    return collate_fn([task[idx] for idx in range(len(task))])
  File "/usr/local/lib/python3.6/dist-packages/torchmeta-1.2.1-py3.6.egg/torchmeta/utils/data/task.py", line 57, in __getitem__
    return Subset.__getitem__(self, index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataset.py", line 257, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/usr/local/lib/python3.6/dist-packages/torchmeta-1.2.1-py3.6.egg/torchmeta/utils/data/task.py", line 44, in __getitem__
    return ConcatDataset.__getitem__(self, index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataset.py", line 207, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/usr/local/lib/python3.6/dist-packages/torchmeta-1.2.1-py3.6.egg/torchmeta/datasets/omniglot.py", line 259, in __getitem__
    image = self.transform(image)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 70, in __call__
    img = t(img)
  File "/usr/local/lib/python3.6/dist-packages/torchmeta-1.2.1-py3.6.egg/torchmeta/transforms/augmentations.py", line 30, in __call__
    self.expand, self.center)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/functional.py", line 729, in rotate
    return img.rotate(angle, resample, expand, center, fillcolor=fill)
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2005, in rotate
    return self.transform((w, h), AFFINE, matrix, resample, fillcolor=fillcolor)
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2299, in transform
    im = new(self.mode, size, fillcolor)
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2505, in new
    return im._new(core.fill(mode, size, color))
TypeError: function takes exactly 1 argument (3 given)
```

**Comment by ximingxing** [comment]
Hello, I ran your code, how do I solve this problem?

**Comment by tristandeleu** [comment]
Hi! Can you give me your version of Pillow (`pip show Pillow`)?
I think there might be something that changed in Pillow 7.0 that is causing some issues, and that might be related. If you have Pillow >= 7.0, then download the latest version of Torchmeta (1.2.2) with:
```
pip uninstall Pillow
pip install --upgrade torchmeta
```

**Comment by ximingxing** [comment]
you are right, i have a highly versoin of torch which >=1.40, i have fix it, thanks for your help!
